---
- name: Deploy web server
  hosts: servers
  become: yes

  tasks:
    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy website index.html
      copy:
        src: /home/ubuntu/web_server_deployment_ansible/site/
        dest: /var/www/html/

